### ISSUE TITLE
Error in 0.16.1

### ISSUE THREAD

**Issue by jpellman** [bids-standard/legacy-validator#110]
Recently I upgraded the BIDS validator to 0.16.1 on one of our servers.  When I tried to point it to a directory, I got the following error:

/usr/local/lib/node_modules/bids-validator/validators/session.js:50
    all_files = new Set(subject_files);
                    ^
ReferenceError: Set is not defined
    at missingSessionFiles (/usr/local/lib/node_modules/bids-validator/validators/session.js:50:21)
    at /usr/local/lib/node_modules/bids-validator/validators/bids.js:187:50
    at /usr/local/lib/node_modules/bids-validator/node_modules/async/lib/async.js:52:16
    at done (/usr/local/lib/node_modules/bids-validator/node_modules/async/lib/async.js:246:17)
    at /usr/local/lib/node_modules/bids-validator/node_modules/async/lib/async.js:44:16
    at /usr/local/lib/node_modules/bids-validator/validators/bids.js:180:33
    at NIFTI (/usr/local/lib/node_modules/bids-validator/validators/nii.js:220:5)
    at /usr/local/lib/node_modules/bids-validator/validators/bids.js:178:29
    at Gunzip.<anonymous> (/usr/local/lib/node_modules/bids-validator/utils/files.js:126:21)
    at Gunzip.EventEmitter.emit (events.js:95:17)

Any idea what might be going on?  Does your code left-pad at any point?

**Comment by constellates** [comment]
Hey @jpellman sorry for the inconvenience. I don't believe this was caused by the Kik/left-pad incident. A recent feature we added used the javascript Set keyword that doesn't have great support at this time. I believe it was added to node at some point along the v4.x.x series. 

Pull #109 should fix this issue once it's merged. Until then your best bet would be to either update the version of node you're using, try pointing to the branch in that PR directly or install an older version of the validator through NPM. Hopefully the merge will be in a published soon.

**Comment by chrisgorgo** [comment]
I have merged this PR - wait 5 minutes for the npm to be updated.

**Comment by constellates** [comment]
Thanks Chris. @jpellman let me know if that resolved your issue.

**Comment by jpellman** [comment]
Hi @constellates ,

I'm now receiving this error:

/usr/local/lib/node_modules/bids-validator/validators/session.js:48
        for (var file of subject) {
                      ^^
SyntaxError: Unexpected identifier
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/bids-validator/validators/bids.js:9:15)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)

**Comment by constellates** [comment]
Taking a look now. What version of node are you running?

**Comment by jpellman** [comment]
v0.10.25

2016-03-24 13:42 GMT-04:00 constellates notifications@github.com:

**Comment by chrisgorgo** [comment]
This version is quite out of date. Is it possible to upgrade it to 4.4.*
(current Long Term Support) on your system?

**Comment by jpellman** [comment]
Sure.  I was actually able to upgrade to Node.js 5.3.0 quite readily.  It might be useful to note somewhere though that this is a suggested course of action for desktop users, or that you don't support certain versions of Node.js, since the version that I had installed was packaged with Ubuntu.

**Comment by constellates** [comment]
Yea we should make a support policy. I'll open an issue later today with some recommendations so we can start talking about it.
