### ISSUE TITLE
gulp build is currently broken

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#112]
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/home/ubuntu/bids-validator/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (/home/ubuntu/bids-validator/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1534:11)
    at croak (eval at <anonymous> (/home/ubuntu/bids-validator/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2026:9)
    at token_error (eval at <anonymous> (/home/ubuntu/bids-validator/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2034:9)
    at expect_token (eval at <anonymous> (/home/ubuntu/bids-validator/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2047:9)
    at expect (eval at <anonymous> (/home/ubuntu/bids-validator/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2050:36)
    at regular_for (eval at <anonymous> (/home/ubuntu/bids-validator/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2280:9)
    at for_ (eval at <anonymous> (/home/ubuntu/bids-validator/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2276:16)
    at eval (eval at <anonymous> (/home/ubuntu/bids-validator/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2158:24)
    at eval (eval at <anonymous> (/home/ubuntu/bids-validator/node_modules/gulp-uglify/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2073:24)

gulp build returned exit code 1

**Comment by constellates** [comment]
I'm taking a look at this now.

**Comment by rwblair** [comment]
I was able to run gulp build successfully commenting out the call to uglify in gulpfile.js.

**Comment by constellates** [comment]
Yea I forgot to comment back on this bug, but there's a PR open to fix this. I previously added a "for of" loop and uglify isn't able to minify those. I believe we can add a polyfill earlier in the build chain if we want to use those, but they don't have a huge benefit anyways.

**Comment by constellates** [comment]
Closing. Builds are working again on Circle CI and gh-pages is running the latest version.
