### ISSUE TITLE
there is a bug with 1.6.1 

### ISSUE THREAD

**Issue by a3sha2** [bids-standard/legacy-validator#1197]
bids-validator@1.6.1

/usr/lib/node_modules/bids-validator/utils/issues/issue.js:37
  this.key = issue.key
                   ^

TypeError: Cannot read property 'key' of undefined
    at new Issue (/usr/lib/node_modules/bids-validator/utils/issues/issue.js:37:20)
    at NIFTI (/usr/lib/node_modules/bids-validator/validators/nifti/nii.js:435:9)
    at /usr/lib/node_modules/bids-validator/validators/nifti/validate.js:42:13
    at Gunzip.<anonymous> (/usr/lib/node_modules/bids-validator/utils/files/readNiftiHeader.js:51:7)
    at Gunzip.emit (events.js:198:13)
    at Gunzip.EventEmitter.emit (domain.js:448:20)
    at addChunk (_stream_readable.js:288:12)
    at readableAddChunk (_stream_readable.js:269:11)
    at Gunzip.Readable.push (_stream_readable.js:224:10)
    at Gunzip.Transform.push (_stream_transform.js:151:32)

**Comment by sappelhoff** [comment]
thanks @a3sha2, can you please specify how you ran bids-validator (docker, CLI, web), and on what data? Does your validator produce this issue on all BIDS datasets you tested, or only one? Does the issue persist after you update the bids-validator to the most recent version? Perhaps trying to validate https://github.com/bids-standard/bids-examples/blob/master/eeg_matchingpennies with your setup would be a good.

**Comment by a3sha2** [comment]
Hi @sappelhoff  thank you very much. I used both docker image and also ordinary setup on linux. Both gave the same error for v1.6.0/1 but v1.5.0 is working perfectly 

this is from docker image v1.6.0
```bids-validator@1.6.1

TypeError: Cannot read property 'key' of undefined
    at new Issue (/src/utils/issues/issue.js:37:20)
    at NIFTI (/src/validators/nifti/nii.js:435:9)
    at /src/validators/nifti/validate.js:42:13
    at Gunzip.<anonymous> (/src/utils/files/readNiftiHeader.js:51:7)
    at Gunzip.emit (events.js:223:5)
    at Gunzip.EventEmitter.emit (domain.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Gunzip.Readable.push (_stream_readable.js:224:10)
    at Gunzip.Transform.push (_stream_transform.js:150:32)in.js:475:20)
    at addChunk (_stream_readable.js:309:12)
    at readableAddChunk (_stream_readable.js:290:11)
    at Gunzip.Readable.push (_stream_readable.js:224:10)
    at Gunzip.Transform.push (_stream_transform.js:150:32)```

**Comment by sappelhoff** [comment]
- by `ordinary setup on linux`, do you mean `npm install --global bids-validator`?
- the most recent version is `1.6.2` can you please update your installation and try again?
- what did the validator output say when running on https://github.com/bids-standard/bids-examples/blob/master/eeg_matchingpennies ?
- can you try validating using the online validator and report back, please? https://bids-standard.github.io/bids-validator/

**Comment by effigies** [comment]
@a3sha2 https://github.com/bids-standard/bids-validator/compare/v1.5.0...v1.6.0 is a big diff to try to sieve through to find a culprit. Can you check other [releases](https://github.com/bids-standard/bids-validator/releases) in that range to narrow down the transition? Also, is this a public dataset or one that you could share?

**Comment by a3sha2** [comment]
sorry for late response @effigies  I was using v1.6.0/1. Then I switched  to current 1.6.2 and it is working perfectly
the data I was testing include ASL
