### ISSUE TITLE
Uninterpretable error on bids upload

### ISSUE THREAD

**Issue by Shotgunosine** [bids-standard/legacy-validator#1301]
Hi all,

I was trying to upload a dataset to openneuro through the web interface and got the following error:

Error: 11 FILE
Internal error. SOME VALIDATION STEPS MAY NOT HAVE OCCURRED
REASON:
Arguments to path.resolve must be strings; please help the BIDS team and community by opening an issue at (https://github.com/bids-standard/bids-validator/issues) with the evidence here.

EVIDENCE:
TypeError: Arguments to path.resolve must be strings at Object.p.resolve (https://openneuro.org/assets/vendor.f06e9078.js:96:151724) at a$e (https://openneuro.org/assets/vendor.f06e9078.js:96:2321400) at Object.l$e (https://openneuro.org/assets/vendor.f06e9078.js:96:2323956) at https://openneuro.org/assets/vendor.f06e9078.js:96:2335646

I can't really make heads or tails of it. Happy to provide the dataset via some other means if that's helpful.

**Comment by nellh** [comment]
> Hi all,
> 
> I was trying to upload a dataset to openneuro through the web interface and got the following error:
> 
> Error: 11 FILE
> Internal error. SOME VALIDATION STEPS MAY NOT HAVE OCCURRED
> REASON:
> Arguments to path.resolve must be strings; please help the BIDS team and community by opening an issue at (https://github.com/bids-standard/bids-validator/issues) with the evidence here.
> 
> EVIDENCE:
> TypeError: Arguments to path.resolve must be strings at Object.p.resolve (https://openneuro.org/assets/vendor.f06e9078.js:96:151724) at a$e (https://openneuro.org/assets/vendor.f06e9078.js:96:2321400) at Object.l$e (https://openneuro.org/assets/vendor.f06e9078.js:96:2323956) at https://openneuro.org/assets/vendor.f06e9078.js:96:2335646
> 
> I can't really make heads or tails of it. Happy to provide the dataset via some other means if that's helpful.

My guess is that the full dataset isn't needed but a file listing with the full paths and filenames would be useful for debugging this.

**Comment by Shotgunosine** [comment]
Is the output of tree sufficient?
[bids_tree.txt](https://github.com/bids-standard/bids-validator/files/6718815/bids_tree.txt)

The only paths I can think of are the intended for paths on the fieldmap files, which look like this:
  "IntendedFor": [
    "ses-visit1/func/sub-20900_ses-visit1_task-MMI_run-1_bold.nii.gz",
    "ses-visit1/func/sub-20900_ses-visit1_task-MMI_run-2_bold.nii.gz",
    "ses-visit1/func/sub-20900_ses-visit1_task-MMI_run-3_bold.nii.gz"
  ],

**Comment by nellh** [comment]
> Is the output of tree sufficient?
> [bids_tree.txt](https://github.com/bids-standard/bids-validator/files/6718815/bids_tree.txt)
> 
> The only paths I can think of are the intended for paths on the fieldmap files, which look like this:
> "IntendedFor": [
> "ses-visit1/func/sub-20900_ses-visit1_task-MMI_run-1_bold.nii.gz",
> "ses-visit1/func/sub-20900_ses-visit1_task-MMI_run-2_bold.nii.gz",
> "ses-visit1/func/sub-20900_ses-visit1_task-MMI_run-3_bold.nii.gz"
> ],

Can you do the same with `find`? Easier to use that output than tree.

**Comment by Shotgunosine** [comment]
Sure
[bids_find.txt](https://github.com/bids-standard/bids-validator/files/6718852/bids_find.txt)

**Comment by Shotgunosine** [comment]
I was able to get the cli working after some fiddling and I'm uploading this dataset to ds003709 through that. The validator threw warnings, but no errors. 

```
(/Users/nielsond/Downloads/mmi_share/jsenv) MH02086115MACLT:mmi_share nielsond$ openneuro upload NIMH-CompyPsych_MMI
? This will create a new dataset, continue? Yes
? Please affirm one of the following: All structural scans have been defaced, obscuring any tissue on or near the face that could potentially be used to recon
struct the facial structure.
bids-validator@1.6.2

	1: [WARN] Not all subjects contain the same files. Each subject should contain the same number of files with the same naming unless some files are known to be missing. (code: 38 - INCONSISTENT_SUBJECTS)
		./sub-23399/ses-visit1/func/sub-23399_ses-visit1_task-MMI_run-1_physio.json
			Evidence: Subject: sub-23399; Missing file: sub-23399_ses-visit1_task-MMI_run-1_physio.json
		./sub-23399/ses-visit1/func/sub-23399_ses-visit1_task-MMI_run-1_physio.tsv.gz
			Evidence: Subject: sub-23399; Missing file: sub-23399_ses-visit1_task-MMI_run-1_physio.tsv.gz
		./sub-23399/ses-visit1/func/sub-23399_ses-visit1_task-MMI_run-2_physio.json
			Evidence: Subject: sub-23399; Missing file: sub-23399_ses-visit1_task-MMI_run-2_physio.json
		./sub-23399/ses-visit1/func/sub-23399_ses-visit1_task-MMI_run-2_physio.tsv.gz
			Evidence: Subject: sub-23399; Missing file: sub-23399_ses-visit1_task-MMI_run-2_physio.tsv.gz
		./sub-23399/ses-visit1/func/sub-23399_ses-visit1_task-MMI_run-3_physio.json
			Evidence: Subject: sub-23399; Missing file: sub-23399_ses-visit1_task-MMI_run-3_physio.json
		./sub-23399/ses-visit1/func/sub-23399_ses-visit1_task-MMI_run-3_physio.tsv.gz
			Evidence: Subject: sub-23399; Missing file: sub-23399_ses-visit1_task-MMI_run-3_physio.tsv.gz
		./sub-23564/ses-visit1/func/sub-23564_ses-visit1_task-MMI_run-1_physio.json
			Evidence: Subject: sub-23564; Missing file: sub-23564_ses-visit1_task-MMI_run-1_physio.json
		./sub-23564/ses-visit1/func/sub-23564_ses-visit1_task-MMI_run-1_physio.tsv.gz
			Evidence: Subject: sub-23564; Missing file: sub-23564_ses-visit1_task-MMI_run-1_physio.tsv.gz
		./sub-23823/ses-visit1/func/sub-23823_ses-visit1_task-MMI_run-1_physio.json
			Evidence: Subject: sub-23823; Missing file: sub-23823_ses-visit1_task-MMI_run-1_physio.json
		./sub-23823/ses-visit1/func/sub-23823_ses-visit1_task-MMI_run-1_physio.tsv.gz
			Evidence: Subject: sub-23823; Missing file: sub-23823_ses-visit1_task-MMI_run-1_physio.tsv.gz
		... and 4 more files having this issue (Use --verbose to see them all).

	Please visit https://neurostars.org/search?q=INCONSISTENT_SUBJECTS for existing conversations about this issue.

	2: [WARN] Not all subjects/sessions/runs have the same scanning parameters. (code: 39 - INCONSISTENT_PARAMETERS)
		./sub-22686/ses-visit1/func/sub-22686_ses-visit1_task-MMI_run-1_bold.nii.gz
		./sub-23017/ses-visit1/func/sub-23017_ses-visit1_task-MMI_run-1_bold.nii.gz
		./sub-23017/ses-visit1/func/sub-23017_ses-visit1_task-MMI_run-2_bold.nii.gz
		./sub-23017/ses-visit1/func/sub-23017_ses-visit1_task-MMI_run-3_bold.nii.gz
		./sub-23108/ses-visit1/func/sub-23108_ses-visit1_task-MMI_run-1_bold.nii.gz
		./sub-23108/ses-visit1/func/sub-23108_ses-visit1_task-MMI_run-2_bold.nii.gz
		./sub-23108/ses-visit1/func/sub-23108_ses-visit1_task-MMI_run-3_bold.nii.gz
		./sub-23303/ses-visit1/func/sub-23303_ses-visit1_task-MMI_run-1_bold.nii.gz
		./sub-23303/ses-visit1/func/sub-23303_ses-visit1_task-MMI_run-2_bold.nii.gz
		./sub-23303/ses-visit1/func/sub-23303_ses-visit1_task-MMI_run-3_bold.nii.gz
		... and 100 more files having this issue (Use --verbose to see them all).

	Please visit https://neurostars.org/search?q=INCONSISTENT_PARAMETERS for existing conversations about this issue.

	3: [WARN] The onset of the last event is after the total duration of the corresponding scan. This design is suspiciously long.  (code: 85 - SUSPICIOUSLY_LONG_EVENT_DESIGN)
		./sub-22686/ses-visit1/func/sub-22686_ses-visit1_task-MMI_events.tsv
		./sub-23017/ses-visit1/func/sub-23017_ses-visit1_task-MMI_events.tsv
		./sub-23017/ses-visit1/func/sub-23017_ses-visit1_task-MMI_events.tsv
		./sub-23108/ses-visit1/func/sub-23108_ses-visit1_task-MMI_events.tsv
		./sub-23108/ses-visit1/func/sub-23108_ses-visit1_task-MMI_events.tsv
		./sub-23303/ses-visit1/func/sub-23303_ses-visit1_task-MMI_events.tsv
		./sub-23399/ses-visit1/func/sub-23399_ses-visit1_task-MMI_events.tsv
		./sub-23549/ses-visit1/func/sub-23549_ses-visit1_task-MMI_events.tsv
		./sub-23549/ses-visit1/func/sub-23549_ses-visit1_task-MMI_events.tsv
		./sub-23564/ses-visit1/func/sub-23564_ses-visit1_task-MMI_events.tsv
		... and 51 more files having this issue (Use --verbose to see them all).

	Please visit https://neurostars.org/search?q=SUSPICIOUSLY_LONG_EVENT_DESIGN for existing conversations about this issue.

(/Users/nielsond/Downloads/mmi_share/jsenv) MH02086115MACLT:mmi_share nielsond$ openneuro upload -i NIMH-CompyPsych_MMI
? This will create a new dataset, continue? Yes
? Please affirm one of the following: All structural scans have been defaced, obscuring any tissue on or near the face that could potentially be used to recon
struct the facial structure.
bids-validator@1.6.2

        Summary:                 Available Tasks:        Available Modalities: 
        1010 Files, 6.6GB        MMI                     T1w                   
        51 - Subjects                                    events                
        1 - Session                                      bold                  
                                                         physio                
                                                         fieldmap              


	If you have any questions, please post on https://neurostars.org/tags/bids.


-----------------------------------------------------
Your OpenNeuro client is out of date (v3.31.1). We strongly recommend you update to the latest version (v3.33.8) for an optimal experience.
-----------------------------------------------------

"ds003709" created
=======================================================================
1013 files to be uploaded with a total size of 6.6 GB
? Begin upload? Yes
=======================================================================

-----------------------------------------------------
Your OpenNeuro client is out of date (v3.31.1). We strongly recommend you update to the latest version (v3.33.8) for an optimal experience.
-----------------------------------------------------

Starting a new upload (39e5c46f) to dataset: 'ds003709'
ds003709 [=---------------------------------------] 2% | ETA: 343s | 23/1013
```

**Comment by sappelhoff** [comment]
@nellh did you want to investigate something here, or is it fine to close now that @Shotgunosine solved his problem?

**Comment by Shotgunosine** [comment]
fine by me to close
