### ISSUE TITLE
unhelpful crash report with CLI validator

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/legacy-validator#1460]
Getting the following crash when running the validator locally. Pretty sure this is an edge case but getting some pointers in the error message could be nice.

Defo not urgent.

Validator works fine on other data sets AFAICT.

This dataset causes no problem to the online validator. 
Attaching error log of the online validator, in case this helps

The dataset is on a private repo on GIN. I can share access if that helps.

Local set up

```bash
npm --version
8.3.1
node --version
v16.14.0
```

Command and output

```bash
bids-validator .            
bids-validator@1.9.3
bids-specification@disable
(node:14218) Warning: Closing directory handle on garbage collection
(Use `node --trace-warnings ...` to show where the warning was created)
Unhandled rejection (
  reason: TypeError: Cannot read properties of undefined (reading 'length')
    at fileArrayToObject (/home/remi/.nvm/versions/node/v16.14.0/lib/node_modules/bids-validator/dist/commonjs/cli.js:98905:33)
    at Object.readDir (/home/remi/.nvm/versions/node/v16.14.0/lib/node_modules/bids-validator/dist/commonjs/cli.js:98900:17)
    at async /home/remi/.nvm/versions/node/v16.14.0/lib/node_modules/bids-validator/dist/commonjs/cli.js:147664:21
```

[CVI-raw_errors.txt](https://github.com/bids-standard/bids-validator/files/8771019/CVI-raw_errors.txt)

**Comment by Remi-Gau** [comment]
will close as this is related to the legacy validator
