### ISSUE TITLE
failure on node 14

### ISSUE THREAD

**Issue by Remi-Gau** [bids-standard/legacy-validator#1711]
See CI on bids-examples

https://github.com/bids-standard/bids-examples/actions/runs/5423616807/jobs/9861800867

Not checked on the examples but bumping the node version of the workflow fixed the fail in CI.

```
npm
7.24.2
node
v14.21.3
bids-validator
/Users/runner/hostedtoolcache/node/14.21.3/x64/lib/node_modules/bids-validator/dist/commonjs/cli.js:133613
    var fd = FormData;
             ^

ReferenceError: FormData is not defined
    at node_modules/then-request/lib/browser.js (/Users/runner/hostedtoolcache/node/14.21.3/x64/lib/node_modules/bids-validator/dist/commonjs/cli.js:133613:14)
    at __require2 (/Users/runner/hostedtoolcache/node/14.21.3/x64/lib/node_modules/bids-validator/dist/commonjs/cli.js:117939:51)
    at Object.<anonymous> (/Users/runner/hostedtoolcache/node/14.21.3/x64/lib/node_modules/bids-validator/dist/commonjs/cli.js:136640:35)
    at Module._compile (internal/modules/cjs/loader.js:1114:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1143:10)
    at Module.load (internal/modules/cjs/loader.js:979:32)
    at Function.Module._load (internal/modules/cjs/loader.js:819:12)
    at Module.require (internal/modules/cjs/loader.js:1003:19)
    at require (internal/modules/cjs/helpers.js:107:18)
    at Object.<anonymous> (/Users/runner/hostedtoolcache/node/14.21.3/x64/lib/node_modules/bids-validator/bin/bids-validator:18:30)<<
```

**Comment by effigies** [comment]
I think the only thing to do is to document the change in minimum NodeJS version. If possible it would be good to mark on the package metadata so that users are warned. The alternative is to unmerge HED updates.

**Comment by sappelhoff** [comment]
Let's bump to minimum 18 and document it.

**Comment by Remi-Gau** [comment]
> Let's bump to minimum 18 and document it.

you on the workflow on the CI of the bids example or as a requirement for the validator?

**Comment by sappelhoff** [comment]
Requirement for the validator :)
