### ISSUE TITLE
ColumnMap errors if key is in prototypes.

### ISSUE THREAD

**Issue by rwblair** [bids-standard/legacy-validator#1824]
> x
Map { "size" => 1 }
> x['size']
Uncaught TypeError: Method get Map.prototype.size called on incompatible receiver #<Map>
    at Proxy.get size (<anonymous>)
    at Reflect.get (<anonymous>)
    at Object.get (file:///home/rwblair/projects/bids/bids-validator/bids-validator/src/types/columns.ts:18:27)
    at <anonymous>:2:2

**Comment by effigies** [comment]
Missed this when posting #1842. Adding my traceback here, which may or may not provide any information beyond what you already have there:

```
error TypeError: Method get Map.prototype.size called on incompatible receiver #<Map>
    at Proxy.get size (<anonymous>)
    at Reflect.get (<anonymous>)
    at Object.get (file:///home/chris/Projects/bids/validator/bids-validator/src/types/columns.ts:18:27)
    at parseTSV (file:///home/chris/Projects/bids/validator/bids-validator/src/files/tsv.ts:36:26)
    at file:///home/chris/Projects/bids/validator/bids-validator/src/schema/context.ts:184:23
    at async BIDSContext.loadColumns (file:///home/chris/Projects/bids/validator/bids-validator/src/schema/context.ts:182:20)
    at async Function.allSettled (<anonymous>)
    at async BIDSContext.asyncLoads (file:///home/chris/Projects/bids/validator/bids-validator/src/schema/context.ts:204:5)
    at async validate (file:///home/chris/Projects/bids/validator/bids-validator/src/validators/bids.ts:78:5)
    at async file:///home/chris/Projects/bids/validator/bids-validator/src/tests/local/common.ts:27:14
```
