### ISSUE TITLE
Cannot parse TSV file with column header "size"

### ISSUE THREAD

**Issue by effigies** [bids-standard/legacy-validator#1842]
We have some index columns that are declared missing because one of the columns is size. See, for example https://github.com/bids-standard/bids-examples/blob/master/ieeg_visual/sub-01/ses-01/ieeg/sub-01_ses-01_electrodes.tsv

Checking the debug output from https://github.com/bids-standard/bids-validator/blob/fb8353391a8b0d35cf94485107bd523161512453/bids-validator/src/schema/context.ts#L178-L186

Shows:

```
error TypeError: Method get Map.prototype.size called on incompatible receiver #<Map>
    at Proxy.get size (<anonymous>)
    at Reflect.get (<anonymous>)
    at Object.get (file:///home/chris/Projects/bids/validator/bids-validator/src/types/columns.ts:18:27)
    at parseTSV (file:///home/chris/Projects/bids/validator/bids-validator/src/files/tsv.ts:36:26)
    at file:///home/chris/Projects/bids/validator/bids-validator/src/schema/context.ts:184:23
    at async BIDSContext.loadColumns (file:///home/chris/Projects/bids/validator/bids-validator/src/schema/context.ts:182:20)
    at async Function.allSettled (<anonymous>)
    at async BIDSContext.asyncLoads (file:///home/chris/Projects/bids/validator/bids-validator/src/schema/context.ts:204:5)
    at async validate (file:///home/chris/Projects/bids/validator/bids-validator/src/validators/bids.ts:78:5)
    at async file:///home/chris/Projects/bids/validator/bids-validator/src/tests/local/common.ts:27:14
```

**Comment by effigies** [comment]
Same as #1824.
