### ISSUE TITLE
Error 1: [Code 0] INTERNAL ERROR

### ISSUE THREAD

**Issue by liviafiliz** [bids-standard/legacy-validator#1920]
Internal error. SOME VALIDATION STEPS MAY NOT HAVE OCCURRED

NaN KB |
Location:
Reason:
e.match is not a function; please help the BIDS team and community by opening an issue at (https://github.com/bids-standard/bids-validator/issues) with the evidence here.

Evidence:
TypeError: e.match is not a function at tR (https://bids-standard.github.io/bids-validator/_next/static/chunks/pages/index-fd7b49cd618c8128.js:1:69353) at tq (https://bids-standard.github.io/bids-validator/_next/static/chunks/pages/index-fd7b49cd618c8128.js:1:69885) at https://bids-standard.github.io/bids-validator/_next/static/chunks/pages/index-fd7b49cd618c8128.js:1:73101

**Comment by effigies** [comment]
Hi @liviafiliz is this still occurring?
