### ISSUE TITLE
Using the optio --schema master (-s master) is throwing an error

### ISSUE THREAD

**Issue by achilleasNP** [bids-standard/legacy-validator#1927]
Hi, 

The validator is throwing an error when used with the option -s master.
The reason seems to be that newer schemas (> v1.7.0) don't have the file:  top_level_files.yaml
The error is shown below:
```
Unhandled rejection (
  reason: Error: ENOENT: no such file or directory, open 'https://raw.githubusercontent.com/bids-standard/bids-specification/master/src/schema/rules/top_level_files.yaml'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at loadYaml (/home/apitsill/.npm/_npx/ac8852d95638c12f/node_modules/bids-validator/dist/commonjs/cli.js:133775:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async loadSchema2 (/home/apitsill/.npm/_npx/ac8852d95638c12f/node_modules/bids-validator/dist/commonjs/cli.js:133791:22)
    at async schemaRegex (/home/apitsill/.npm/_npx/ac8852d95638c12f/node_modules/bids-validator/dist/commonjs/cli.js:133871:14)
    at async /home/apitsill/.npm/_npx/ac8852d95638c12f/node_modules/bids-validator/dist/commonjs/cli.js:133892:18
).
```

Thanks in advance,
Achilleas

**Comment by nellh** [comment]
Hi, this option has been removed. It was a short experiment to integrate the schema but has since been replaced by a complete alternative validator. You can find [documentation for the schema based validator here](https://github.com/bids-standard/bids-validator/blob/master/bids-validator/src/README.md).
