### ISSUE TITLE
Tests are out of data

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#20]
```
$ npm test

> bids-validator@0.3.3 test /Users/filo/drive/workspace/bids-validator-1
> mocha tests/



  BIDS
    1) should verify that NifTi files are compressed using gzip.

  JSON
    2) should catch missing closing brackets
    3) should have key/value pair for "repetition_time"

  TSV
    ✓ should not allow contiguous spaces
    ✓ should not allow different length rows
    ✓ should not allow headers to begin with numbers


  3 passing (24ms)
  3 failing

  1) BIDS should verify that NifTi files are compressed using gzip.:
     TypeError: path must be a string
      at TypeError (native)
      at Object.fs.readdirSync (fs.js:813:18)
      at getFiles (utils.js:85:20)
      at Object.readDir (utils.js:66:17)
      at Object.module.exports [as BIDS] (validators/bids.js:211:11)
      at Context.<anonymous> (tests/bids.spec.js:18:18)

  2) JSON should catch missing closing brackets:
     TypeError: Cannot read property 'hasOwnProperty' of null
      at repetitionTime (validators/json.js:64:21)
      at Object.module.exports [as JSON] (validators/json.js:27:13)
      at Context.<anonymous> (tests/json.spec.js:7:12)

  3) JSON should have key/value pair for "repetition_time":
     TypeError: callback is not a function
      at Object.module.exports [as JSON] (validators/json.js:31:9)
      at Context.<anonymous> (tests/json.spec.js:14:12)



npm ERR! Test failed.  See above for more details.
```

It seems that the tests are out of date - for example the .nii.gz tests calls the validator with a dictionary of files instead of a dir name.

**Comment by constellates** [comment]
This is my bad. We should be running this before anything makes it to master. All current tests should be passing on the master branch now and the npm version has been updated.
