### ISSUE TITLE
Deno v1.14.9-dev.0: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by mateuszpawlik** [bids-standard/legacy-validator#2095]
I've just tried to execute the Deno-based validator using Deno docker image and got the following error. I tried to use the command from the [documentation](https://github.com/bids-standard/bids-validator/tree/master/bids-validator/src#usage).
```
docker run -ti --rm -v $PWD:/data:ro denoland/deno deno run --allow-read --allow-env https://deno.land/x/bids_validator/bids-validator.ts /data
Warning Implicitly using latest version (v1.14.9-dev.0) for https://deno.land/x/bids_validator/bids-validator.ts
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'split')
    return url.pathname.split('@')[1].split('/')[0]
                                     ^
    at getRemoteVersion (https://deno.land/x/bids_validator@v1.14.9-dev.0/version.ts:50:38)
    at getVersion (https://deno.land/x/bids_validator@v1.14.9-dev.0/version.ts:30:15)
    at parseOptions (https://deno.land/x/bids_validator@v1.14.9-dev.0/setup/options.ts:51:25)
    at main (https://deno.land/x/bids_validator@v1.14.9-dev.0/main.ts:11:25)
    at https://deno.land/x/bids_validator@v1.14.9-dev.0/bids-validator.ts:3:22
```

I tried the latest stable version `v1.14.8`. It took a while without any output, but eventually it executed.
```
docker run -ti --rm -v $PWD:/data:ro denoland/deno deno run --allow-read --allow-env https://deno.land/x/bids_validator@v1.14.8/bids-validator.ts /data

```

**Comment by effigies** [comment]
Fixed in #2077.
