### ISSUE TITLE
Check numerical values are numbers not strings

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#245]
```
/work/01329/poldrack/lonestar/software_lonestar5/nodejs/nodejs-4.4.7/lib/node_modules/bids-validator/validators/nii.js:144
                    var jsonTR = Number((mergedDictionary.RepetitionTime).toFixed(3));
                                                                          ^

TypeError: mergedDictionary.RepetitionTime.toFixed is not a function
    at NIFTI (/work/01329/poldrack/lonestar/software_lonestar5/nodejs/nodejs-4.4.7/lib/node_modules/bids-validator/validators/nii.js:144:75)
    at /work/01329/poldrack/lonestar/software_lonestar5/nodejs/nodejs-4.4.7/lib/node_modules/bids-validator/validators/bids.js:283:29
    at Gunzip.<anonymous> (/work/01329/poldrack/lonestar/software_lonestar5/nodejs/nodejs-4.4.7/lib/node_modules/bids-validator/utils/files.js:135:21)
    at emitOne (events.js:96:13)
    at Gunzip.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:177:18)
    at Gunzip.Readable.push (_stream_readable.js:135:10)
    at Gunzip.Transform.push (_stream_transform.js:128:32)
    at Zlib.callback (zlib.js:598:14)
```

**Comment by chrisgorgo** [comment]
Still happening for JSONS like this:
```
{
  "TaskName": "localizer",
  "RepetitionTime": "2",
  "EchoTime": "0.03",
  "FlipAngle": "90",
  "Manufacturer": "SIEMENS",
  "ManufacturersModelName": "Prisma"
}
```

**Comment by chrisgorgo** [comment]
The solution would be not to include JSON files that do not pass the schema validation in any other checks.
