### ISSUE TITLE
[BUG] RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by oesteban** [bids-standard/legacy-validator#265]
We are seeing this for a dataset:
```
nodejs-4.4.7/lib/node_modules/bids-validator/node_modules/async/dist/async.js:825
        return i < len ? { value: obj[key], key: key } : null;
                         ^

RangeError: Maximum call stack size exceeded
    at next (/work/01329/poldrack/software/nodejs-4.4.7/lib/node_modules/bids-validator/node_modules/async/dist/async.js:825:26)
    at replenish (/work/01329/poldrack/software/nodejs-4.4.7/lib/node_modules/bids-validator/node_modules/async/dist/async.js:872:28)
    at iterateeCallback (/work/01329/poldrack/software/nodejs-4.4.7/lib/node_modules/bids-validator/node_modules/async/dist/async.js:866:17)
    at /work/01329/poldrack/software/nodejs-4.4.7/lib/node_modules/bids-validator/node_modules/async/dist/async.js:843:16
    at NIFTI.async.forEachOf.issues.push.Issue.file (/work/01329/poldrack/software/nodejs-4.4.7/lib/node_modules/bids-validator/validators/nii.js:217:21)
    at replenish (/work/01329/poldrack/software/nodejs-4.4.7/lib/node_modules/bids-validator/node_modules/async/dist/async.js:881:17)
    at iterateeCallback (/work/01329/poldrack/software/nodejs-4.4.7/lib/node_modules/bids-validator/node_modules/async/dist/async.js:866:17)
    at /work/01329/poldrack/software/nodejs-4.4.7/lib/node_modules/bids-validator/node_modules/async/dist/async.js:843:16
    at NIFTI.async.forEachOf.issues.push.Issue.file (/work/01329/poldrack/software/nodejs-4.4.7/lib/node_modules/bids-validator/validators/nii.js:217:21)
    at replenish (/work/01329/poldrack/software/nodejs-4.4.7/lib/node_modules/bids-validator/node_modules/async/dist/async.js:881:17)
```

```
login2.ls5(11)$ bids-validator --version
0.21.0
```

**Comment by chrisgorgo** [comment]
@ntraut I think this was introduced by #262

**Comment by ntraut** [comment]
Yes it is always the same issue: `async.forEach` should be call with a limit in order to avoid too much pending file opérations and the callback should be called with `process.nextTick`.
I think the new issues are introduced because the new versions of async are less tolerant with call stack size limits.
Sorry, I didn't looked for all the calls of `async.forEach` and I cannot do this just now.
