### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#274]
```
$ bids-validator example1
C:\Users\filo\AppData\Roaming\npm\node_modules\bids-validator\validators\nii.js:49
                bvec.split('\n')[2].replace(/^\s+|\s+$/g, '').split(' ').length, // bvec row 3 length
                                   ^

TypeError: Cannot read property 'replace' of undefined
    at NIFTI (C:\Users\filo\AppData\Roaming\npm\node_modules\bids-validator\validators\nii.js:49:36)
    at C:\Users\filo\AppData\Roaming\npm\node_modules\bids-validator\validators\bids.js:281:29
    at Gunzip.<anonymous> (C:\Users\filo\AppData\Roaming\npm\node_modules\bids-validator\utils\files.js:135:21)
    at emitOne (events.js:96:13)
    at Gunzip.emit (events.js:189:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Gunzip.Readable.push (_stream_readable.js:134:10)
    at Gunzip.Transform.push (_stream_transform.js:128:32)
    at Zlib.callback (zlib.js:584:14)
```
[example1.tar.gz](https://github.com/INCF/bids-validator/files/936248/example1.tar.gz)

**Comment by olgn** [comment]
fixed with #277 and #513
