### ISSUE TITLE
ValidatorBreaking on ds208

### ISSUE THREAD

**Issue by suyashdb** [bids-standard/legacy-validator#310]
```
login2.ls5(23)$ /home1/04275/suyashdb/validator_versions/validatorSept11/bids-validator/bin/bids-validator .
/home1/04275/suyashdb/node_modules/ajv/lib/ajv.js:92
      if (!v) throw new Error('no schema with key or ref "' + schemaKeyRef + '"');
              ^

Error: no schema with key or ref "http://json-schema.org/draft-06/schema#"
    at validate (/home1/04275/suyashdb/node_modules/ajv/lib/ajv.js:92:21)
    at validateSchema (/home1/04275/suyashdb/node_modules/ajv/lib/ajv.js:162:19)
    at _addSchema (/home1/04275/suyashdb/node_modules/ajv/lib/ajv.js:288:7)
    at Ajv.compile (/home1/04275/suyashdb/node_modules/ajv/lib/ajv.js:113:21)
    at checkUnits (/home1/04275/suyashdb/validator_versions/validatorSept11/bids-validator/validators/json.js:42:32)
    at /home1/04275/suyashdb/validator_versions/validatorSept11/bids-validator/validators/json.js:22:44
    at Object.parse (/home1/04275/suyashdb/validator_versions/validatorSept11/bids-validator/utils/json.js:29:17)
    at module.exports (/home1/04275/suyashdb/validator_versions/validatorSept11/bids-validator/validators/json.js:20:16)
    at /home1/04275/suyashdb/validator_versions/validatorSept11/bids-validator/validators/bids.js:275:21
    at /home1/04275/suyashdb/validator_versions/validatorSept11/bids-validator/utils/files.js:50:47
```

**Comment by chrisgorgo** [comment]
@nellh Could this be related to https://github.com/INCF/bids-validator/pull/309 ?

**Comment by nellh** [comment]
@suyashdb Have you run npm install since pulling the new master? This is the error you get with the new schema + old ajv.

**Comment by suyashdb** [comment]
@nellh the new master is not generating error for any other dataset. 
Also the older version of validator runs successfully on ds208 without running npm install.

**Comment by chrisgorgo** [comment]
Please try doing npm install to update dependencies nonetheless. It will
help narrowing down what's the problem.

**Comment by suyashdb** [comment]
@chrisfilo @nellh yes after `npm install` there's no more error.
