### ISSUE TITLE
Validate that config file is proper JSON

### ISSUE THREAD

**Issue by suyashdb** [bids-standard/legacy-validator#343]
```
login2.ls5(6)$ bin/bids-validator /corral-repl/utexas/poldracklab/openfmri/inprocess/ds000233/ds000233_R1.0.0/uncompressed/ --c config
/home1/04275/suyashdb/validator_versions/validatorSept11/bids-validator/cli.js:15
            if (issues.errors.length === 1 && issues.errors[0].code === '61') {
                             ^

TypeError: Cannot read property 'length' of undefined
    at /home1/04275/suyashdb/validator_versions/validatorSept11/bids-validator/cli.js:15:30
    at /home1/04275/suyashdb/validator_versions/validatorSept11/bids-validator/validators/bids.js:36:17
    at /home1/04275/suyashdb/validator_versions/validatorSept11/bids-validator/utils/options.js:20:17
    at /home1/04275/suyashdb/validator_versions/validatorSept11/bids-validator/utils/options.js:51:17
    at /home1/04275/suyashdb/validator_versions/validatorSept11/bids-validator/utils/options.js:35:21
    at /home1/04275/suyashdb/validator_versions/validatorSept11/bids-validator/utils/files.js:46:47
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```
Following is the content of config file.
```
login2.ls5(7)$ more config.json
{
    "error": ["NO_T1W"],
    "ignoredFiles": ['derivatives/*']
}
```

Dataset used: `ds000233_R1.0.0`

**Comment by chrisgorgo** [comment]
What if you try double quotes around derivatives/*?

Best,
Chris

**Comment by suyashdb** [comment]
It works when i use double quotes. Will send  a PR with this example in `README.md`
