### ISSUE TITLE
0.25.6 crashes with obscure traceback if path to config is wrong

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#397]
```shell
bids@rolando:~/test-redo-fromsourcedata/dbic/QA$ /usr/bin/bids-validator  --verbose $PWD
This dataset appears to be BIDS compatible.
        Summary:                  Available Tasks:                     Available Modalities: 
        23 Files, 138.49MB        TODO: full task name for rest        T1w                   
        1 - Subject                                                    dwi                   
        1 - Session                                                    bold                  

bids@rolando:~/test-redo-fromsourcedata/dbic/QA$ /usr/bin/bids-validator -c /wrong/path  --verbose $PWD
/usr/lib/node_modules/bids-validator/cli.js:15
            if (issues.errors.length === 1 && issues.errors[0].code === '61') {
                             ^

TypeError: Cannot read property 'length' of undefined
    at /usr/lib/node_modules/bids-validator/cli.js:15:30
    at /usr/lib/node_modules/bids-validator/validators/bids.js:38:17
    at /usr/lib/node_modules/bids-validator/utils/options.js:20:17
    at /usr/lib/node_modules/bids-validator/utils/options.js:51:17
    at /usr/lib/node_modules/bids-validator/utils/options.js:35:21
    at /usr/lib/node_modules/bids-validator/utils/files.js:47:47
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
bids@rolando:~/test-redo-fromsourcedata/dbic/QA$ bids-validator --version
0.25.6
```
and works good if correct ;)
```shell
bids@rolando:~/test-redo-fromsourcedata/dbic/QA$ /usr/bin/bids-validator -c ~/heudiconv/heudiconv/heuristics/reproin_validator.cfg  --verbose $PWD
This dataset appears to be BIDS compatible.
        Summary:                  Available Tasks:                     Available Modalities: 
        23 Files, 138.49MB        TODO: full task name for rest        T1w                   
        1 - Subject                                                    dwi                   
        1 - Session                                                    bold ```

**Comment by sappelhoff** [comment]
@yarikoptic is this issue still persistent with the current version of `bids-validator`?
