### ISSUE TITLE
CLI version crashing 

### ISSUE THREAD

**Issue by suyashdb** [bids-standard/legacy-validator#421]
https://github.com/INCF/bids-validator/blob/master/cli.js#L44

```
sr16-d788a04670:bids-validator suyashdb$ bin/bids-validator ~/Downloads/ds213/uncompressed/
/Users/suyashdb/Downloads/bids-validator/cli.js:44
        var type = (color==red ? 'ERR': 'WARN');
                           ^

```
```
ReferenceError: red is not defined
    at logIssues (/Users/suyashdb/Downloads/bids-validator/cli.js:44:28)
    at /Users/suyashdb/Downloads/bids-validator/cli.js:26:17
    at /Users/suyashdb/Downloads/bids-validator/validators/bids.js:434:17
    at /Users/suyashdb/Downloads/bids-validator/node_modules/async/dist/async.js:473:16
    at iterateeCallback (/Users/suyashdb/Downloads/bids-validator/node_modules/async/dist/async.js:980:24)
    at /Users/suyashdb/Downloads/bids-validator/node_modules/async/dist/async.js:958:16
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
sr16-d788a04670:bids-validator suyashdb$
```

**Comment by chrisgorgo** [comment]
We'll be fixed in 0.25.12 which should hit npm soon. Sorry for that.
