### ISSUE TITLE
The "fd" argument must be of type number. Received type undefined

### ISSUE THREAD

**Issue by dorianps** [bids-standard/legacy-validator#483]
Fresh new install of bids-validator. 
Checking a dataset mostly in bids format (maybe missing the dataset_description and participants file).  Data are converted by someone else, so not sure what exactly is the problem. Here is the error (running as root, so no permission problems). Any idea?

```
internal/validators.js:113
    throw err;
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "fd" argument must be of type number. Received type undefined
    at Object.read (fs.js:448:3)
    at /usr/lib/node_modules/bids-validator/utils/files.js:252:20
    at FSReqWrap.oncomplete (fs.js:145:20)
```

**Comment by chrisgorgo** [comment]
Thanks for reporting. This one looks tricky. Could you try upgrading Node and reinstalling bids-validator with its latest dependencies? Is the dataset on a network drive?

If that doesn't work I would need a sample dataset to try to replicate the issue.

**Comment by dorianps** [comment]
`nodejs` was just installed. History below:

```
 992  curl --silent --location https://rpm.nodesource.com/setup_10.x | sudo bash -
  993  sudo yum install -y nodejs
  994  npm install -g bids-validator
  995  which bids-validator
  997  bids-validator converted/
  1002  bids-validator converted

node --version
v10.6.0
```

Unfortunately, I can't share any file from the dataset, very sensitive legal dept... And it's huge anyway, 1800+ subjects with multiple timepoints. Anything I can do on my side?

**Comment by dorianps** [comment]
Here is an example of the path if it helps:

`converted/sub-T907978419/ses-01/anat/sub-T907978419_ses-01_run-01_T1w.nii.gz`

**Comment by chrisgorgo** [comment]
I created a branch that should be better at capturing such situations and giving feedback on which file in particular bids-validator had troubles reading. Could you try it out? https://github.com/chrisfilo/bids-validator/tree/enh/better_error_reporting

**Comment by dorianps** [comment]
Need a bit of help, not even sure where is the installation path. How can I install if from local after git clone? Even uninstallation is not working well with `npm uninstall bids-validator`...

**Comment by chrisgorgo** [comment]
`npm install -g chrisfilo/bids-validator#enh/better_error_reporting`

**Comment by dorianps** [comment]
Installing from branch is not working, will need to check later if there is any specific problem with `npm` permissions, unless you know what is going on. Thanks.

```
[root@mri dorian]# npm install -g bids-validator
/usr/bin/bids-validator -> /usr/lib/node_modules/bids-validator/bin/bids-validator
+ bids-validator@0.26.15
added 109 packages from 69 contributors in 12.144s
[root@mri dorian]# npm uninstall -g bids-validator
removed 109 packages in 1.045s
[root@mri dorian]# npm install -g chrisfilo/bids-validator#enh/better_error_reporting
npm ERR! code 128
npm ERR! Command failed: /opt/anaconda2/bin/git clone --depth=1 -q -b enh/better_error_reporting git://github.com/chrisfilo/bids-validator.git /root/.npm/_cacache/tmp/git-clone-91c88a1f
npm ERR! fatal: could not create leading directories of '/root/.npm/_cacache/tmp/git-clone-91c88a1f': Permission denied
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2018-07-06T20_17_42_987Z-debug.log
[root@mri dorian]#
```

**Comment by chrisgorgo** [comment]
No idea. The installation worked for me just fine.

**Comment by jasmainak** [comment]
you need to try it on a dataset from [BIDS-examples](https://github.com/INCF/BIDS-examples) first. If you get the same error, you have an installation problem. Otherwise, we need to dig deeper

**Comment by dorianps** [comment]
First, I haven't installed yet Chris's fork. But so far The BIDS-examples work. And any folder I point to produces a normal output. i.e. failing from a quick test. What I think is going on is that the number of files in my BIDS folder is extremely large, hence the script is failing. It takes a few seconds to fail, in fact, it's not immediate. And I can surely say that the two main files, dataset_description and participants, are not there, even though the folder structure looks like BIDS.

Is this enough to help you find the error or do you need me to still try the new fork anyway? At this point I know that it will need some work to reorganize the data to comply with BIDS in full.

P.s. A collateral question. If I have lesion masks from stroke patients, where should I put them to make a BIDS app recognize them?

**Comment by chrisgorgo** [comment]
> Is this enough to help you find the error or do you need me to still try the new fork anyway? At this point I know that it will need some work to reorganize the data to comply with BIDS in full.

No. My best guess is that one of the nifti files in your dataset is corrupted or not available due to a filesystem issue. The fork should help figure out which one.

> P.s. A collateral question. If I have lesion masks from stroke patients, where should I put them to make a BIDS app recognize them?

See https://docs.google.com/document/d/1Wwc4A6Mow4ZPPszDIWfCUCRNstn7d_zzaWPcfcHmgI4/edit#heading=h.9146wuepclkt - please mind this is still a draft.

**Comment by dorianps** [comment]
Your branch works as expected I think (some IDs edited before posting):

```
        1: Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset. Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)
                ./bids.tar
                        Evidence: bids.tar
                ./bids.tar.md5
                        Evidence: bids.tar.md5
                ./filelist.txt
                        Evidence: filelist.txt
                ./sub-T993722328/ses-91/anat/sub-T993722328_ses-91_run-91_T1w.nii.gz.json
                        Evidence: sub-T993722328_ses-91_run-91_T1w.nii.gz.json
                ./sub-T993722328/ses-91/anat/sub-T993722328_ses-91_run-91_T2w.nii.gz.json
                        Evidence: sub-T993722328_ses-91_run-91_T2w.nii.gz.json
                ./sub-T993722328/ses-91/anat/sub-T993722328_ses-91_run-92_T1w.nii.gz.json
                        Evidence: sub-T993722328_ses-91_run-92_T1w.nii.gz.json
                ./sub-T993833998/ses-91/anat/sub-T993833998_ses-91_run-91_T1w.nii.gz.json
                        Evidence: sub-T993833998_ses-91_run-91_T1w.nii.gz.json
                ./sub-T993833998/ses-91/anat/sub-T993833998_ses-91_run-91_T2w.nii.gz.json
                        Evidence: sub-T993833998_ses-91_run-91_T2w.nii.gz.json
                ./sub-T993833998/ses-91/anat/sub-T993833998_ses-91_run-92_T1w.nii.gz.json
                        Evidence: sub-T993833998_ses-91_run-92_T1w.nii.gz.json
                ./sub-T993833998/ses-92/anat/sub-T993833998_ses-92_run-91_T1w.nii.gz.json
                        Evidence: sub-T993833998_ses-92_run-91_T1w.nii.gz.json
                ... and 5381 more files having this issue (Use --verbose to see them all).

        2: This file ends in the .gz extension but is not actually gzipped. (code: 28 - GZ_NOT_GZIPPED)
                ./sub-NT994898/ses-91/anat/sub-NT994898_ses-91_run-91_T1w.nii.gz
                ./sub-NT994898/ses-92/anat/sub-NT994898_ses-92_run-91_T1w.nii.gz
                ./sub-NT994898/ses-93/anat/sub-NT994898_ses-93_run-91_T1w.nii.gz
                ./sub-NT994899/ses-91/anat/sub-NT994899_ses-91_run-91_T1w.nii.gz
                ./sub-NT994899/ses-92/anat/sub-NT994899_ses-92_run-91_T1w.nii.gz
                ./sub-NT994899/ses-93/anat/sub-NT994899_ses-93_run-91_T1w.nii.gz
                ./sub-NT994819/ses-91/anat/sub-NT994819_ses-91_run-91_T1w.nii.gz
                ./sub-NT994819/ses-93/anat/sub-NT994819_ses-93_run-91_T1w.nii.gz
                ./sub-NT994811/ses-91/anat/sub-NT994811_ses-91_run-91_T1w.nii.gz
                ./sub-NT994811/ses-92/anat/sub-NT994811_ses-92_run-91_T1w.nii.gz
                ... and 276 more files having this issue (Use --verbose to see them all).

        3: We were unable to read this file. Make sure it is not corrupted, incorrectly named or incorrectly symlinked. (code: 44 - FILE_READ)
                ./sub-ST311417/ses-91/anat/sub-ST311417_ses-91_run-91_T2w.nii.gz
                ./sub-ST311417/ses-92/anat/sub-ST311417_ses-92_run-91_T1w.nii.gz
                ./sub-ST311417/ses-92/anat/sub-ST311417_ses-92_run-91_T2w.nii.gz
                ./sub-ST311417/ses-93/anat/sub-ST311417_ses-93_run-91_T1w.nii.gz
                ./sub-ST311417/ses-93/anat/sub-ST311417_ses-93_run-91_T2w.nii.gz
                ./sub-ST311417/ses-93/anat/sub-ST311417_ses-93_run-92_T1w.nii.gz
                ./sub-ST311417/ses-93/anat/sub-ST311417_ses-93_run-92_T2w.nii.gz
                ./sub-ST311876/ses-91/anat/sub-ST311876_ses-91_run-91_T1w.nii.gz
                ./sub-ST311876/ses-92/anat/sub-ST311876_ses-92_run-91_T1w.nii.gz
                ./sub-ST311876/ses-92/anat/sub-ST311876_ses-92_run-91_T2w.nii.gz
                ... and 9981 more files having this issue (Use --verbose to see them all).

        4: The compulsory file /dataset_description.json is missing. See Section 8.1 of the BIDS specification. (code: 57 - DATASET_DESCRIPTION_JSON_MISSING)

        5: sform_code and qform_code in the image header are 9. The image/file will be considered invalid or assumed to be in LAS orientation. (code: 69 - SFORM_AND_QFORM_IN_IMAGE_HEADER_ARE_ZERO)
                ./sub-NT994822/ses-92/anat/sub-NT994822_ses-92_run-91_T1w.nii.gz
                ./sub-NT994826/ses-92/anat/sub-NT994826_ses-92_run-91_T1w.nii.gz
                ./sub-NT995954/ses-92/anat/sub-NT995954_ses-92_run-91_T1w.nii.gz
                ./sub-NT995981/ses-92/anat/sub-NT995981_ses-92_run-91_T1w.nii.gz

        1: Not all subjects contain the same files. Each subject should contain the same number of files with the same naming unless some files are known to be missing. (code: 38 - INCONSISTENT_SUBJECTS)
                ./sub-NT994898/ses-91/anat/sub-NT994898_ses-91_run-91_T2w.nii.gz
                ./sub-NT994898/ses-91/anat/sub-NT994898_ses-91_run-92_T1w.nii.gz
                ./sub-NT994898/ses-91/anat/sub-NT994898_ses-91_run-92_T2w.nii.gz
                ./sub-NT994898/ses-91/anat/sub-NT994898_ses-91_run-93_T1w.nii.gz
                ./sub-NT994898/ses-91/anat/sub-NT994898_ses-91_run-93_T2w.nii.gz
                ./sub-NT994898/ses-91/anat/sub-NT994898_ses-91_run-94_T1w.nii.gz
                ./sub-NT994898/ses-91/anat/sub-NT994898_ses-91_run-94_T2w.nii.gz
                ./sub-NT994898/ses-91/anat/sub-NT994898_ses-91_run-95_T1w.nii.gz
                ./sub-NT994898/ses-91/anat/sub-NT994898_ses-91_run-96_T1w.nii.gz
                ./sub-NT994898/ses-91/anat/sub-NT994898_ses-91_run-97_T1w.nii.gz
                ... and 133645 more files having this issue (Use --verbose to see them all).

        2: Not all subjects/sessions/runs have the same scanning parameters. (code: 39 - INCONSISTENT_PARAMETERS)
                ./sub-NT994822/ses-92/anat/sub-NT994822_ses-92_run-91_T1w.nii.gz
                ./sub-NT994826/ses-92/anat/sub-NT994826_ses-92_run-91_T1w.nii.gz
                ./sub-NT995954/ses-92/anat/sub-NT995954_ses-92_run-91_T1w.nii.gz
                ./sub-NT995981/ses-92/anat/sub-NT995981_ses-92_run-91_T1w.nii.gz
                ./sub-ST999527/ses-91/anat/sub-ST999527_ses-91_run-91_T1w.nii.gz
                ./sub-ST999527/ses-91/anat/sub-ST999527_ses-91_run-91_T2w.nii.gz
                ./sub-ST999527/ses-91/anat/sub-ST999527_ses-91_run-92_T1w.nii.gz
                ./sub-ST999527/ses-91/anat/sub-ST999527_ses-91_run-92_T2w.nii.gz
                ./sub-ST999891/ses-91/anat/sub-ST999891_ses-91_run-91_T2w.nii.gz
                ./sub-ST999891/ses-92/anat/sub-ST999891_ses-92_run-91_T2w.nii.gz
                ... and 2796 more files having this issue (Use --verbose to see them all).

        Summary:                     Available Tasks:        Available Modalities:
        19466 Files, 152.26GB                                T1w
        1879 - Subjects                                      T2w
        19 - Sessions
```

**Comment by dorianps** [comment]
Your branch worked as expected.

```
       1: Files with such naming scheme are not part of BIDS specification. This error is most commonly caused by typos in file names that make them not BIDS compatible. Please consult the specification and make sure your files are named correctly. If this is not a file naming issue (for example when including files not yet covered by the BIDS specification) you should include a ".bidsignore" file in your dataset. Please note that derived (processed) data should be placed in /derivatives folder and source data (such as DICOMS or behavioural logs in proprietary formats) should be placed in the /sourcedata folder. (code: 1 - NOT_INCLUDED)
                ./bids.tar
                        Evidence: bids.tar
                ./bids.tar.md5
                        Evidence: bids.tar.md5
                ./filelist.txt
                        Evidence: filelist.txt
                ./sub-R003722328/ses-01/anat/sub-R003722328_ses-01_run-01_T1w.nii.gz.json
                        Evidence: sub-R003722328_ses-01_run-01_T1w.nii.gz.json
                ./sub-R003722328/ses-01/anat/sub-R003722328_ses-01_run-01_T2w.nii.gz.json
                        Evidence: sub-R003722328_ses-01_run-01_T2w.nii.gz.json
                ./sub-R003722328/ses-01/anat/sub-R003722328_ses-01_run-02_T1w.nii.gz.json
                        Evidence: sub-R003722328_ses-01_run-02_T1w.nii.gz.json
                ./sub-R003833008/ses-01/anat/sub-R003833008_ses-01_run-01_T1w.nii.gz.json
                        Evidence: sub-R003833008_ses-01_run-01_T1w.nii.gz.json
                ./sub-R003833008/ses-01/anat/sub-R003833008_ses-01_run-01_T2w.nii.gz.json
                        Evidence: sub-R003833008_ses-01_run-01_T2w.nii.gz.json
                ./sub-R003833008/ses-01/anat/sub-R003833008_ses-01_run-02_T1w.nii.gz.json
                        Evidence: sub-R003833008_ses-01_run-02_T1w.nii.gz.json
                ./sub-R003833008/ses-02/anat/sub-R003833008_ses-02_run-01_T1w.nii.gz.json
                        Evidence: sub-R003833008_ses-02_run-01_T1w.nii.gz.json
                ... and 5381 more files having this issue (Use --verbose to see them all).

        2: This file ends in the .gz extension but is not actually gzipped. (code: 28 - GZ_NOT_GZIPPED)
                ./sub-NT004808/ses-01/anat/sub-NT004808_ses-01_run-01_T1w.nii.gz
                ./sub-NT004808/ses-02/anat/sub-NT004808_ses-02_run-01_T1w.nii.gz
                ./sub-NT004808/ses-03/anat/sub-NT004808_ses-03_run-01_T1w.nii.gz
                ./sub-NT004802/ses-01/anat/sub-NT004802_ses-01_run-01_T1w.nii.gz
                ./sub-NT004802/ses-02/anat/sub-NT004802_ses-02_run-01_T1w.nii.gz
                ./sub-NT004802/ses-03/anat/sub-NT004802_ses-03_run-01_T1w.nii.gz
                ./sub-NT004810/ses-01/anat/sub-NT004810_ses-01_run-01_T1w.nii.gz
                ./sub-NT004810/ses-03/anat/sub-NT004810_ses-03_run-01_T1w.nii.gz
                ./sub-NT004811/ses-01/anat/sub-NT004811_ses-01_run-01_T1w.nii.gz
                ./sub-NT004811/ses-02/anat/sub-NT004811_ses-02_run-01_T1w.nii.gz
                ... and 276 more files having this issue (Use --verbose to see them all).

        3: We were unable to read this file. Make sure it is not corrupted, incorrectly named or incorrectly symlinked. (code: 44 - FILE_READ)
                ./sub-ST311417/ses-01/anat/sub-ST311417_ses-01_run-01_T2w.nii.gz
                ./sub-ST311417/ses-02/anat/sub-ST311417_ses-02_run-01_T1w.nii.gz
                ./sub-ST311417/ses-02/anat/sub-ST311417_ses-02_run-01_T2w.nii.gz
                ./sub-ST311417/ses-03/anat/sub-ST311417_ses-03_run-01_T1w.nii.gz
                ./sub-ST311417/ses-03/anat/sub-ST311417_ses-03_run-01_T2w.nii.gz
                ./sub-ST311417/ses-03/anat/sub-ST311417_ses-03_run-02_T1w.nii.gz
                ./sub-ST311417/ses-03/anat/sub-ST311417_ses-03_run-02_T2w.nii.gz
                ./sub-ST311876/ses-01/anat/sub-ST311876_ses-01_run-01_T1w.nii.gz
                ./sub-ST311876/ses-02/anat/sub-ST311876_ses-02_run-01_T1w.nii.gz
                ./sub-ST311876/ses-02/anat/sub-ST311876_ses-02_run-01_T2w.nii.gz
                ... and 2281 more files having this issue (Use --verbose to see them all).

        4: The compulsory file /dataset_description.json is missing. See Section 8.1 of the BIDS specification. (code: 57 - DATASET_DESCRIPTION_JSON_MISSING)

        5: sform_code and qform_code in the image header are 0. The image/file will be considered invalid or assumed to be in LAS orientation. (code: 60 - SFORM_AND_QFORM_IN_IMAGE_HEADER_ARE_ZERO)
                ./sub-NT004822/ses-02/anat/sub-NT004822_ses-02_run-01_T1w.nii.gz
                ./sub-NT004826/ses-02/anat/sub-NT004826_ses-02_run-01_T1w.nii.gz
                ./sub-NT005054/ses-02/anat/sub-NT005054_ses-02_run-01_T1w.nii.gz
                ./sub-NT005081/ses-02/anat/sub-NT005081_ses-02_run-01_T1w.nii.gz

        1: Not all subjects contain the same files. Each subject should contain the same number of files with the same naming unless some files are known to be missing. (code: 38 - INCONSISTENT_SUBJECTS)
                ./sub-NT004808/ses-01/anat/sub-NT004808_ses-01_run-01_T2w.nii.gz
                ./sub-NT004808/ses-01/anat/sub-NT004808_ses-01_run-02_T1w.nii.gz
                ./sub-NT004808/ses-01/anat/sub-NT004808_ses-01_run-02_T2w.nii.gz
                ./sub-NT004808/ses-01/anat/sub-NT004808_ses-01_run-03_T1w.nii.gz
                ./sub-NT004808/ses-01/anat/sub-NT004808_ses-01_run-03_T2w.nii.gz
                ./sub-NT004808/ses-01/anat/sub-NT004808_ses-01_run-04_T1w.nii.gz
                ./sub-NT004808/ses-01/anat/sub-NT004808_ses-01_run-04_T2w.nii.gz
                ./sub-NT004808/ses-01/anat/sub-NT004808_ses-01_run-05_T1w.nii.gz
                ./sub-NT004808/ses-01/anat/sub-NT004808_ses-01_run-06_T1w.nii.gz
                ./sub-NT004808/ses-01/anat/sub-NT004808_ses-01_run-07_T1w.nii.gz
                ... and 133645 more files having this issue (Use --verbose to see them all).

        2: Not all subjects/sessions/runs have the same scanning parameters. (code: 32 - INCONSISTENT_PARAMETERS)
                ./sub-NT004822/ses-02/anat/sub-NT004822_ses-02_run-01_T1w.nii.gz
                ./sub-NT004826/ses-02/anat/sub-NT004826_ses-02_run-01_T1w.nii.gz
                ./sub-NT005054/ses-02/anat/sub-NT005054_ses-02_run-01_T1w.nii.gz
                ./sub-NT005081/ses-02/anat/sub-NT005081_ses-02_run-01_T1w.nii.gz
                ./sub-ST000527/ses-01/anat/sub-ST000527_ses-01_run-01_T1w.nii.gz
                ./sub-ST000527/ses-01/anat/sub-ST000527_ses-01_run-01_T2w.nii.gz
                ./sub-ST000527/ses-01/anat/sub-ST000527_ses-01_run-02_T1w.nii.gz
                ./sub-ST000527/ses-01/anat/sub-ST000527_ses-01_run-02_T2w.nii.gz
                ./sub-ST000801/ses-01/anat/sub-ST000801_ses-01_run-01_T2w.nii.gz
                ./sub-ST000801/ses-02/anat/sub-ST000801_ses-02_run-01_T2w.nii.gz
                ... and 2706 more files having this issue (Use --verbose to see them all).

        Summary:                     Available Tasks:        Available Modalities:
        12466 Files, 152.26GB                                T1w
        1870 - Subjects                                      T2w
        10 - Sessions


````

**Comment by chrisgorgo** [comment]
Awesome - thanks for reporting and testing.
