### ISSUE TITLE
Uncaught exceptions are creating invalid issues

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#582]
An exception in a different part of the code led to an invalid issue passed down the line

```
C:\gdrive\workspace\bids-validator\utils\issues\index.js:74
        categorized[issue.code].files = []
                                      ^

TypeError: Cannot set property 'files' of undefined
    at Object.format (C:\gdrive\workspace\bids-validator\utils\issues\index.js:74:39)
    at C:\gdrive\workspace\bids-validator\validators\bids\fullTest.js:509:43
    at C:\gdrive\workspace\bids-validator\node_modules\async\dist\async.js:473:16
    at iterateeCallback (C:\gdrive\workspace\bids-validator\node_modules\async\dist\async.js:992:24)
    at C:\gdrive\workspace\bids-validator\node_modules\async\dist\async.js:969:16
    at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by olgn** [comment]
@chrisfilo do you happen to have a reproduction case?

**Comment by chrisgorgo** [comment]
This dataset https://drive.google.com/file/d/19RYauOI9Zqd97T_yKpJfzt3KrZTVsX1M/view?usp=sharing prior to this fix https://github.com/INCF/bids-validator/pull/581
