### ISSUE TITLE
cli SynatxError: Unexpected Token

### ISSUE THREAD

**Issue by suyashdb** [bids-standard/legacy-validator#635]
Tried fixing it, but the unexpected token error keeps generating for almost all `console.log` calls. Doesn't like the `,` i believe. 

It didn't work on our data-set hence tried reproducing the error with bids-example dataset. Following is the error:

```
-bash-4.2$ bids-validator bids-examples/ds000248
/usr/lib/node_modules/bids-validator/cli.js:26
            ),
            ^

SyntaxError: Unexpected token )
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/lib/node_modules/bids-validator/bin/bids-validator:34:1)
-bash-4.2$ bids-validator -v
1.0.5
```

**Comment by nellh** [comment]
You'll see this error if you're on an unsupported older version of Node.js. This syntax is supported in Node.js 8.2 or later.
