### ISSUE TITLE
Cannot read property 'includes' of undefined

### ISSUE THREAD

**Issue by chrisgorgo** [bids-standard/legacy-validator#670]
```
 [ERR] Internal error. SOME VALIDATION STEPS MAY NOT HAVE OCCURRED (code: 0 - INTERNAL ERROR)
                .undefined
                        Evidence: TypeError: Cannot read property 'includes' of undefined
    at TSV (/home/users/chrisgor/openneuro-cli/node_modules/bids-validator/validators/tsv/tsv.js:17:16)
    at utils.files.readFile.then.contents (/home/users/chrisgor/openneuro-cli/node_modules/bids-validator/validators/tsv/validate.js:34:11)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
```

**Comment by chrisgorgo** [comment]
This was caused by lack or read permissions to one of the TSV files. We should handle this more gracefully.

**Comment by rwblair** [comment]
related #186

**Comment by sappelhoff** [comment]
I edited #186 to properly reflect this issue as well.

Closing this one as a dupe now.
