### ISSUE TITLE
hardcoded assumption of openneuro's S3 git-annex special remote

### ISSUE THREAD

**Issue by yarikoptic** [bids-standard/legacy-validator#769]
I am trying to run fmriprep (1.3.2, which runs validator first) and for starters didn't even get any data file yet for the BIDS dataset I datalad installed from `///labs/haxby/raiders`.  That dataset does not have files available from S3 but do have them available via git-annex otherwise (from our datasets.datalad.org http server).  Running fmriprep results in
```shell
$> ./fmriprep-test raiders raiders-fmriprep participant
Making sure the input data is BIDS compliant (warnings can be ignored in most cases).
fatal: Path 'd99/14a/MD5E-s6938049--aa604e6677a573a11b5c5b26cce231d0.nii.gz.log.rmet' does not exist in 'git-annex'
child_process.js:656
    throw err;
    ^

Error: Command failed: git show git-annex:d99/14a/MD5E-s6938049--aa604e6677a573a11b5c5b26cce231d0.nii.gz.log.rmet
fatal: Path 'd99/14a/MD5E-s6938049--aa604e6677a573a11b5c5b26cce231d0.nii.gz.log.rmet' does not exist in 'git-annex'

    at checkExecSyncError (child_process.js:616:11)
    at Object.execSync (child_process.js:653:13)
    at Object.callGitAnnex (/usr/lib/node_modules/bids-validator/utils/files/remoteFiles.js:142:23)
    at Object.getRemoteMetadata (/usr/lib/node_modules/bids-validator/utils/files/remoteFiles.js:183:17)
    at Object.getRemotesInfo (/usr/lib/node_modules/bids-validator/utils/files/remoteFiles.js:158:27)
    at Object.getAnnexedFile (/usr/lib/node_modules/bids-validator/utils/files/remoteFiles.js:26:31)
    at /usr/lib/node_modules/bids-validator/utils/files/testFile.js:24:25
    at FSReqWrap.oncomplete (fs.js:155:5)
Traceback (most recent call last):
  File "/usr/local/miniconda/bin/fmriprep", line 11, in <module>
    load_entry_point('fmriprep==1.3.2', 'console_scripts', 'fmriprep')()
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 358, in main
    validate_input_dir(exec_env, opts.bids_dir, opts.participant_label)
  File "/usr/local/miniconda/lib/python3.7/site-packages/fmriprep/cli/run.py", line 549, in validate_input_dir
    subprocess.check_call(['bids-validator', bids_dir, '-c', temp.name])
  File "/usr/local/miniconda/lib/python3.7/subprocess.py", line 341, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bids-validator', 'raiders', '-c', '/tmp/tmpkuiwe5ko']' returned non-zero exit status 1.
Sentry is attempting to send 0 pending error messages
Waiting up to 2.0 seconds
Press Ctrl-C to quit
```
so validator tries to deduce versions/location of those missing files on S3.  I think that if no .rmet file found (unless validator implements some other annex access strategies, like a simple url at least), it should just blow with a message like "file X is under git-annex but no content available locally. Use git-annex (or DataLad) to retrieve it first", or could even may be run `git-annex or datalad get` on it (ideally optionally) if datalad or git-annex is available (fmriprep docker image does carry them).

**Comment by effigies** [comment]
Have you tried with the latest bids-validator? It may be the case that we need to upgrade the validator in fMRIPrep's images.

**Comment by yarikoptic** [comment]
docker version:
```
$> docker run --rm -v $PWD:$PWD bids/validator $PWD/raiders
/bin/sh: git-annex: not found                  
child_process.js:644
    throw err;
    ^

Error: Command failed: git-annex lookupkey sub-rid000005/anat/sub-rid000005_run-01_T1w.nii.gz
/bin/sh: git-annex: not found

    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at Object.callGitAnnex (/src/utils/files/remoteFiles.js:142:23)
    at Object.getLookupKey (/src/utils/files/remoteFiles.js:166:17)
    at Object.getRemotesInfo (/src/utils/files/remoteFiles.js:156:28)
    at Object.getAnnexedFile (/src/utils/files/remoteFiles.js:26:31)
    at /src/utils/files/testFile.js:24:25
    at FSReqWrap.oncomplete (fs.js:153:5)

$> docker run --rm -v $PWD:$PWD bids/validator -v          
0.0.0
```
ok, installing via npm 
```
(git)smaug:~/proj/bids/BIDS-apps/shub[master]singularity/bids-reproducing-769
$> npm install bids-validator

> date-fns@2.0.0-alpha.27 postinstall /home/yoh/proj/bids/BIDS-apps/shub/singularity/bids-reproducing-769/node_modules/date-fns
> node ./docs/printV2Notice.js


🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

  Thank you for testing (⩗) date-fns v2!

  In v2 we've introduced a number of breaking changes
  that make date-fns even more consistent and reliable.
  Please read the changelog carefully: https://git.io/fxCWb

  Please support us at Open Collective: https://opencollective.com/date-fns

🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥

npm WARN saveError ENOENT: no such file or directory, open '/home/yoh/proj/bids/BIDS-apps/shub/singularity/bids-reproducing-769/package.json'
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN enoent ENOENT: no such file or directory, open '/home/yoh/proj/bids/BIDS-apps/shub/singularity/bids-reproducing-769/package.json'
npm WARN bids-reproducing-769 No description
npm WARN bids-reproducing-769 No repository field.
npm WARN bids-reproducing-769 No README data
npm WARN bids-reproducing-769 No license field.

+ bids-validator@1.2.3
added 136 packages from 124 contributors in 5.89s

$> node_modules/.bin/bids-validator raiders 
fatal: Path 'd99/14a/MD5E-s6938049--aa604e6677a573a11b5c5b26cce231d0.nii.gz.log.rmet' does not exist in 'git-annex'
child_process.js:644
    throw err;
    ^

Error: Command failed: git show git-annex:d99/14a/MD5E-s6938049--aa604e6677a573a11b5c5b26cce231d0.nii.gz.log.rmet
fatal: Path 'd99/14a/MD5E-s6938049--aa604e6677a573a11b5c5b26cce231d0.nii.gz.log.rmet' does not exist in 'git-annex'

    at checkExecSyncError (child_process.js:601:13)
    at Object.execSync (child_process.js:641:13)
    at Object.callGitAnnex (/home/yoh/proj/bids/BIDS-apps/shub/singularity/bids-reproducing-769/node_modules/bids-validator/utils/files/remoteFiles.js:142:23)
    at Object.getRemoteMetadata (/home/yoh/proj/bids/BIDS-apps/shub/singularity/bids-reproducing-769/node_modules/bids-validator/utils/files/remoteFiles.js:183:17)
    at Object.getRemotesInfo (/home/yoh/proj/bids/BIDS-apps/shub/singularity/bids-reproducing-769/node_modules/bids-validator/utils/files/remoteFiles.js:158:27)
    at Object.getAnnexedFile (/home/yoh/proj/bids/BIDS-apps/shub/singularity/bids-reproducing-769/node_modules/bids-validator/utils/files/remoteFiles.js:26:31)
    at /home/yoh/proj/bids/BIDS-apps/shub/singularity/bids-reproducing-769/node_modules/bids-validator/utils/files/testFile.js:24:25
    at FSReqWrap.oncomplete (fs.js:153:5)
```
so seems to reproduce

**Comment by yarikoptic** [comment]
ran into it again with the fmriprep 1.5.0 image... so the scare persist

**Comment by nellh** [comment]
Updating to 1.3.5 should fix this issue, S3 remote validation is not enabled without a flag now, and further improvements to it will follow some refactoring of the feature.
