### ISSUE TITLE
Hangs with dangling symlink

### ISSUE THREAD

**Issue by mih** [bids-standard/legacy-validator#92]
If the validator hits a symlink that points straight to Valhalla it hangs forever and eventually exists with an exception -- without producing any other output. I guess it should simply report a dangling symlink as such. Those can be present of one uses git-annex for data management.

**Comment by rwblair** [comment]
Error I'm seeing with a dangling symlink:

fs.js:892
  return binding.stat(pathModule._makeLong(path));
                 ^

Error: ENOENT: no such file or directory, stat 'tests/data/BIDS-examples-1.0.0-rc3u4/ds001//sub-01/anat/dangling.sym'
    at Error (native)
    at Object.fs.statSync (fs.js:892:18)
    at getFiles (/Users/rblair/projects/bids-validator/utils/files.js:95:16)
    at getFiles (/Users/rblair/projects/bids-validator/utils/files.js:96:13)
    at getFiles (/Users/rblair/projects/bids-validator/utils/files.js:96:13)
    at Object.readDir (/Users/rblair/projects/bids-validator/utils/files.js:73:17)
    at Object.BIDS.start [as BIDS](/Users/rblair/projects/bids-validator/validators/bids.js:30:21)
    at module.exports (/Users/rblair/projects/bids-validator/cli.js:8:15)
    at Object.<anonymous> (/Users/rblair/projects/bids-validator/bin/bids-validator:20:18)
    at Module._compile (module.js:413:34)

Different function may need to be used to tell if a file is a symlink, fs.stat' fs.Stats object wont contain an isSymbolicLink attribute:
https://nodejs.org/dist/latest-v4.x/docs/api/fs.html#fs_class_fs_stats
https://nodejs.org/dist/latest-v4.x/docs/api/fs.html#fs_fs_lstat_path_callback

**Comment by constellates** [comment]
Thanks @rwblair . That looks like the root of this issue. I have some time to take a look at this now, so let me know if you've already started writing a fix so we're not doubling up.

**Comment by rwblair** [comment]
Have not started on it yet so you should be good.

**Comment by constellates** [comment]
Added new PR #156
